### ISSUE TITLE
Did open error

### ISSUE THREAD

**Issue by lachhebo** [lachhebo/dedukti-editor#1]
I'm using atom 1.27 on fedora 28 with atom-ide-ui, language-ocaml and prettier-atom extensions installed.

I have written a server for .dk file with full text synchronisation.
When I'm opening a large .dk file, the didchange notifications is sent many times. The more the file is large, the more atom is sending didchange notifications.

An example :

    For a 15 lines file. the notification is only sent once.
    For a 72 lines file. the notification is sent twice.
    For a 296 lines file, the notification is sent 6 times.

I think a solution would be to switch to incremental synchronisation which is not bugged. 

When i checked the log file of the server, i have seen an error 
[process_input]: Not_found
When a tried to remove from the server the handler for didopen messages, the error disappeared. Hence i think an other solution would be to debug  this handler.

**Comment by ejgallego** [comment]
I think this can be closed.
